### ISSUE TITLE
I tried to create a Rapids 2015 report card but something went wrong

### ISSUE THREAD

**Issue by danielboniface** [denverpost/report-card#5]
I followed the "how to" guide and I think it should be here: http://extras.denverpost.com/app/report-card/group/rapids-2015.html

But it's not. @freejoe76

**Comment by freejoe76** [comment]
@danielboniface There was an issue with the deploy script, it's fixed now and http://extras.denverpost.com/app/report-card/group/rapids-2015.html is live. Thanks!

**Comment by danielboniface** [comment]
Sweet, thanks @freejoe76!
